allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  esbuild: set this to true or false
  prisma: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
minimumReleaseAgeExclude:
  - framer-motion@12.39.0
  - motion-dom@12.39.0
  - motion-utils@12.39.0
  - tsx@4.22.2
